### ISSUE TITLE
Create our own custom Pluggable Authentication Modules system

### ISSUE THREAD

**Issue by traverseda** [rationalist-diaspora/admin-panel#1]
I recommend we make simple, yaml, "identity" files, for managing the complicated relations between users and their various accounts.

```yaml
name: traverseda@outsidecontext.solutions
alt-names: ["With Dread But Cautious Optimism", "Alex Davies"]
avatar: https://example.com/example.png

auth-methods:
 - !md5sum 4e716a77dd8ffec1052547bc1d74fc7b
 - !ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3FzPo+9JkzB9NOBbs91KNlwAbtCL/Ug3tAfMUClVJYBh9EQEf1rHcDzZQzFHP8QoImQ7EY4iAaXeF2+FTJ+9f41Ya//Vbod1XvZ2OGfUlDOUKKC8AT9gadH02QEXp+eD8yfKSZNLeZOnCnrbq0S0jWQvhJWyDFGK7eZxbtDM+JjqhKkuhtFdj/1v4dsl4TVM/IRjX5DxYsubnUDtNxazvy3kRgldqFY3fjPPzDRD+Mhu7x7D9zaa//dX7dER8kNEJB/3tWwn63/xZJRHGeXQU8TJK41oVA1JxR9+wyvzKzXgEcCxxD+UFthspCqoor6hQkXBRzkEB/X47ecEKxxRt alex@localhost.no-domain-set.aliant
 - !not-md5sum {salt:'adawd',iterations:'10^10^10',hash:'a7176879495151b12702a294af0ac9dd'}

```

An organization could look like

```yaml
name: coolpeopleclub@outsidecontext.solutions

auth-methods:
 - !identity https://outsidecontext.solutions/users/traverseda #Points to the above identity file...

edit-auth: #Permissions required to edit this identity...
 - !md5sum 4e716a77dd8ffec1052547bc1d74fc7b

```
